# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f828fae89912732507773e2fd6438ab7f8a1135a73a3669bb70c516a2d2f525edd0dbd945c6eec79f9d990065802cc7aeccdc750696249dd67e173990c603a52

test:
  secret_key_base: 190754c1a3a8052bfb300b88252aea5a27ac244ac07d7f59659fc381bb9998e8fc7a49c91bd17bee9b5a37196eaec79ef29c7f63d48a6dbd10454a59fe4f4a7a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
